### PR TITLE
increase default page size as suggested in https://github.com/bio-guo…

### PR DESCRIPTION
**Pull request by jhpoelen**
…da/preston/issues/21#issuecomment-531955680

increase default page size as suggested in https://github.com/bio-guoda/preston/issues/21#issuecomment-531955680 .

### CODE REVIEW

**Comment by mdoering** [comment]
I can't see a reason to increase the default. Anyone who wants more can supply the `limit` parameter, otherwise it's wise to keep the default low to not consume unnecessary resources.

**Comment by mdoering** [comment]
see https://www.gbif.org/developer/summary#common

**Comment by jhpoelen** [comment]
@mdoering ok - thanks for considering it. I'll keep paging at the default limit when retrieving all datasets.

**Comment by MattBlissett** [comment]
It's completely fine to increase the limit if you wish to retrieve all datasets.

`https://api.gbif.org/v1/dataset?limit=1000` and so on. The highest value for the limit is 1000 in this case, but it varies across different API calls, and you should ideally check the number actually returned.

**Comment by jhpoelen** [comment]
@MattBlissett understood - thanks for clarifying. I'd like to respect the resource usage concern and keep my code as simple as possible so fewer tests are needed. 

For what it is worth: I do have to say that BHL-like approach to publishing a catalog/registry as a tsv file (e.g., https:////www.biodiversitylibrary.org/data/item.txt) would make for an fast and less error-prone full registry integration. Our use case fits into the "give-me-everything" use cases, which I expect might be a bit of an edge case. 

Thanks again for your replies and for all the good work in keeping gbif up and running!

**Comment by mdoering** [comment]
Thanks @jhpoelen I very much like your idea of publishing a list of all registered datasets in one CSV/TSV file. I think its sth we should consider, and its simple to do.

**Comment by mdoering** [comment]
@jhpoelen if you want to page through all datasets it is actually less resource intensive the larger the page sizes are. So please use limit=1000 in your case, it makes sense.

There are many cases though when people just like to see a few records and returning 1000 Taxa for example by default is unreasonable. I would even argue to reduce the default to just 10

**Pull request closed without merging**
